working_dir: /mnt/xvdf
core_config: /etc/stellar/stellar-core.cfg
backup_dir: /var/lib/stellar/backups
s3_bucket: stellar002-core-backups
s3_path: testnet
verifying_gpg_key: backups@stellar.org
signing_gpg_key: backups@stellar.org
signing_gpg_pass: 'SuperSecurePassPhrase!@#$'

